sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGuz38VyWXRJHS8872u
    access-key-secret: sZYqgnOJ2qUdPKhr8uPYmRv5zm1nT8
    bucket-name: guoshenghuizhao
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx8cfc4b9bdebc0591
    secret: 6dc9a2ac67ed1482142ce528bf6b489d
